"""empty message

Revision ID: 24cb83841413
Revises: b7d38cb3a823
Create Date: 2022-11-10 21:05:54.566620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24cb83841413'
down_revision = 'b7d38cb3a823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tbl_predictions_game'), 'tbl_predictions', ['game'], unique=False)
    op.create_index(op.f('ix_tbl_predictions_user'), 'tbl_predictions', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_predictions_user'), table_name='tbl_predictions')
    op.drop_index(op.f('ix_tbl_predictions_game'), table_name='tbl_predictions')
    # ### end Alembic commands ###
