"""empty message

Revision ID: 45e4b1c2f7a9
Revises: 24cb83841413
Create Date: 2022-11-10 21:59:02.065390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45e4b1c2f7a9'
down_revision = '24cb83841413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_predictions', sa.Column('user_email', sa.String(), nullable=False))
    op.add_column('tbl_predictions', sa.Column('game_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_index('ix_tbl_predictions_game', table_name='tbl_predictions')
    op.drop_index('ix_tbl_predictions_user', table_name='tbl_predictions')
    op.create_index(op.f('ix_tbl_predictions_game_id'), 'tbl_predictions', ['game_id'], unique=False)
    op.create_index(op.f('ix_tbl_predictions_user_email'), 'tbl_predictions', ['user_email'], unique=False)
    op.drop_constraint('tbl_predictions_user_fkey', 'tbl_predictions', type_='foreignkey')
    op.drop_constraint('tbl_predictions_game_fkey', 'tbl_predictions', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_predictions', 'tbl_users', ['user_email'], ['email'])
    op.create_foreign_key(None, 'tbl_predictions', 'tbl_games', ['game_id'], ['id'])
    op.drop_column('tbl_predictions', 'game')
    op.drop_column('tbl_predictions', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_predictions', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tbl_predictions', sa.Column('game', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tbl_predictions', type_='foreignkey')
    op.drop_constraint(None, 'tbl_predictions', type_='foreignkey')
    op.create_foreign_key('tbl_predictions_game_fkey', 'tbl_predictions', 'tbl_games', ['game'], ['id'])
    op.create_foreign_key('tbl_predictions_user_fkey', 'tbl_predictions', 'tbl_users', ['user'], ['email'])
    op.drop_index(op.f('ix_tbl_predictions_user_email'), table_name='tbl_predictions')
    op.drop_index(op.f('ix_tbl_predictions_game_id'), table_name='tbl_predictions')
    op.create_index('ix_tbl_predictions_user', 'tbl_predictions', ['user'], unique=False)
    op.create_index('ix_tbl_predictions_game', 'tbl_predictions', ['game'], unique=False)
    op.drop_column('tbl_predictions', 'game_id')
    op.drop_column('tbl_predictions', 'user_email')
    # ### end Alembic commands ###
