"""empty message

Revision ID: 545579df67d7
Revises: 8f8a5308a749
Create Date: 2022-11-10 18:19:52.304905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '545579df67d7'
down_revision = '8f8a5308a749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_predictions',
    sa.Column('game', postgresql.UUID(as_uuid=True), nullable=True, primaty_key=True),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('actual_score', sa.String(), nullable=True),
    sa.Column('predicted_score', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game'], ['tbl_games.id'], ),
    sa.ForeignKeyConstraint(['user'], ['tbl_users.email'], ),
    sa.PrimaryKeyConstraint('user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_predictions')
    # ### end Alembic commands ###
