"""Migration message

Revision ID: 7a4507752cef
Revises: 
Create Date: 2022-11-09 20:21:54.847036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a4507752cef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_games',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('team_a', sa.String(), nullable=False),
    sa.Column('team_b', sa.String(), nullable=False),
    sa.Column('score', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_games_date'), 'tbl_games', ['date'], unique=False)
    op.create_index(op.f('ix_tbl_games_id'), 'tbl_games', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_games_id'), table_name='tbl_games')
    op.drop_index(op.f('ix_tbl_games_date'), table_name='tbl_games')
    op.drop_table('tbl_games')
    # ### end Alembic commands ###
