"""empty message

Revision ID: 87e9d44a76f1
Revises: 1572fb6b53a5
Create Date: 2022-12-02 19:24:49.740025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e9d44a76f1'
down_revision = '1572fb6b53a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prediction_start_timestamp', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('prediction_end_timestamp', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_rounds', schema=None) as batch_op:
        batch_op.drop_column('prediction_end_timestamp')
        batch_op.drop_column('prediction_start_timestamp')

    # ### end Alembic commands ###
