"""empty message

Revision ID: a9a5ce9eaaf4
Revises: be4ca81d5308
Create Date: 2022-11-21 00:39:54.232768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a5ce9eaaf4'
down_revision = 'be4ca81d5308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_games', schema=None) as batch_op:
        batch_op.drop_index('ix_tbl_games_match_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_games', schema=None) as batch_op:
        batch_op.create_index('ix_tbl_games_match_date', ['match_date'], unique=False)

    # ### end Alembic commands ###
