"""empty message

Revision ID: b7d38cb3a823
Revises: 545579df67d7
Create Date: 2022-11-10 18:20:57.090730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7d38cb3a823'
down_revision = '545579df67d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_predictions', 'game',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_predictions', 'game',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
