"""empty message

Revision ID: bc785f84af9b
Revises: d8e800012fe5
Create Date: 2022-12-04 15:12:05.083515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc785f84af9b'
down_revision = 'd8e800012fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_ranking', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('past_ranking', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.drop_column('past_ranking')
        batch_op.drop_column('current_ranking')

    # ### end Alembic commands ###
