"""empty message

Revision ID: be4ca81d5308
Revises: e522d6ce9090
Create Date: 2022-11-20 23:57:04.276700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4ca81d5308'
down_revision = 'e522d6ce9090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_games', schema=None) as batch_op:
        batch_op.alter_column('group', new_column_name='match_group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('match_group')

    # ### end Alembic commands ###
