"""empty message

Revision ID: d0830df4e3fc
Revises: 
Create Date: 2022-11-19 22:22:49.122168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0830df4e3fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_games',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('team_a', sa.String(), nullable=False),
    sa.Column('team_b', sa.String(), nullable=False),
    sa.Column('score', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('group', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tbl_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tbl_games_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tbl_games_id'), ['id'], unique=False)

    op.create_table('tbl_users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tbl_users_id'), ['id'], unique=False)

    op.create_table('tbl_predictions',
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('game_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('actual_score', sa.String(), nullable=True),
    sa.Column('predicted_score', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['tbl_games.id'], ),
    sa.ForeignKeyConstraint(['user_email'], ['tbl_users.email'], ),
    sa.PrimaryKeyConstraint('user_email', 'game_id')
    )
    with op.batch_alter_table('tbl_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tbl_predictions_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tbl_predictions_user_email'), ['user_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tbl_predictions_user_email'))
        batch_op.drop_index(batch_op.f('ix_tbl_predictions_game_id'))

    op.drop_table('tbl_predictions')
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tbl_users_id'))

    op.drop_table('tbl_users')
    with op.batch_alter_table('tbl_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tbl_games_id'))
        batch_op.drop_index(batch_op.f('ix_tbl_games_date'))

    op.drop_table('tbl_games')
    # ### end Alembic commands ###
