"""empty message

Revision ID: d8e800012fe5
Revises: 87e9d44a76f1
Create Date: 2022-12-02 20:29:20.113421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e800012fe5'
down_revision = '87e9d44a76f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_rounds', schema=None) as batch_op:
        batch_op.alter_column('prediction_start_timestamp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('prediction_end_timestamp',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_rounds', schema=None) as batch_op:
        batch_op.alter_column('prediction_end_timestamp',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('prediction_start_timestamp',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
