"""empty message

Revision ID: ddf149f15dc0
Revises: 
Create Date: 2022-11-14 08:50:29.270158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddf149f15dc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_games',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('team_a', sa.String(), nullable=False),
    sa.Column('team_b', sa.String(), nullable=False),
    sa.Column('score', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_games_date'), 'tbl_games', ['date'], unique=False)
    op.create_index(op.f('ix_tbl_games_id'), 'tbl_games', ['id'], unique=False)
    op.create_table('tbl_users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_tbl_users_id'), 'tbl_users', ['id'], unique=False)
    op.create_table('tbl_predictions',
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('game_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('actual_score', sa.String(), nullable=True),
    sa.Column('predicted_score', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['tbl_games.id'], ),
    sa.ForeignKeyConstraint(['user_email'], ['tbl_users.email'], ),
    sa.PrimaryKeyConstraint('user_email', 'game_id')
    )
    op.create_index(op.f('ix_tbl_predictions_game_id'), 'tbl_predictions', ['game_id'], unique=False)
    op.create_index(op.f('ix_tbl_predictions_user_email'), 'tbl_predictions', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_predictions_user_email'), table_name='tbl_predictions')
    op.drop_index(op.f('ix_tbl_predictions_game_id'), table_name='tbl_predictions')
    op.drop_table('tbl_predictions')
    op.drop_index(op.f('ix_tbl_users_id'), table_name='tbl_users')
    op.drop_table('tbl_users')
    op.drop_index(op.f('ix_tbl_games_id'), table_name='tbl_games')
    op.drop_index(op.f('ix_tbl_games_date'), table_name='tbl_games')
    op.drop_table('tbl_games')
    # ### end Alembic commands ###
