"""empty message

Revision ID: e522d6ce9090
Revises: 950bb927717c
Create Date: 2022-11-20 23:37:38.793789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e522d6ce9090'
down_revision = '950bb927717c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_games', schema=None) as batch_op:
        batch_op.alter_column('date', new_column_name='match_date')
        batch_op.drop_index('ix_tbl_games_date')
        batch_op.create_index(batch_op.f('ix_tbl_games_match_date'), ['match_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_tbl_games_match_date'))
        batch_op.create_index('ix_tbl_games_date', ['date'], unique=False)
        batch_op.drop_column('match_date')

    # ### end Alembic commands ###
